export const VERIFY_USER = 'VERIFY_USER';
export const PARSE_DARA = 'PARSE_DARA';
export const TRANSFORM_DATA_DEFAULT_FORMAT = 'TRANSFORM_DATA_DEFAULT_FORMAT';
export const GET_COUNTRY_FIELDS = 'GET_COUNTRY_FIELDS';
export const MODIFY_VERIFIED_OBJECT_COUNTRY_FIELDS = 'MODIFY_VERIFIED_OBJECT_COUNTRY_FIELDS';
export const REMOVE_UNNECESSARY_FIELDS = 'REMOVE_UNNECESSARY_FIELDS';
export const CHECK_REQUIRED_FIDLDS = 'CHECK_REQUIRED_FIDLDS';
export const GET_COUNTRIES = 'GET_COUNTRIES';
